const languagesObj: any = {
  af: "Afrikaans (South Africa) ",
  sq: "Albanian (Albania) ",
  ar: "Arabic (Saudi Arabia) ",
  hy: "Armenian (Armenia) ",
  az: "Azeri (Cyrillic) (Azerbaijan) ",
  eu: "Basque (Spain) ",
  be: "Belarusian (Belarus) ",
  bs: "Bosnian (Bosnia and Herzegovina) ",
  bg: "Bulgarian (Bulgaria) ",
  ca: "Catalan (Spain) ",
  zh: "Chinese ",
  hr: "Croatian (Croatia) ",
  cs: "Czech (Czech Republic) ",
  dv: "Divehi (Maldives) ",
  nl: "Dutch (Netherlands) ",
  en: "English (United States) ",
  eo: "Esperanto ",
  et: "Estonian (Estonia) ",
  fo: "Faroese (Faroe Islands) ",
  fa: "Farsi ",
  fi: "Finnish (Finland) ",
  fr: "French (France) ",
  mk: "FYRO Macedonian (Former Yugoslav Republic of Macedonia) ",
  gl: "Galician (Spain) ",
  ka: "Georgian (Georgia) ",
  de: "German (Germany) ",
  el: "Greek (Greece) ",
  gu: "Gujarati (India) ",
  he: "Hebrew (Israel) ",
  hi: "Hindi (India) ",
  hu: "Hungarian (Hungary) ",
  is: "Icelandic (Iceland) ",
  id: "Indonesian (Indonesia) ",
  it: "Italian (Italy) ",
  ja: "Japanese (Japan) ",
  lv: "Latvian (Latvia) ",
  lt: "Lithuanian (Lithuania) ",
  kn: "Kannada (India) ",
  kk: "Kazakh (Kazakhstan) ",
  kok: "Konkani (India) ",
  ko: "Korean (Korea) ",
  ky: "Kyrgyz (Kyrgyzstan) ",
  ms: "Malay (Malaysia) ",
  mt: "Maltese (Malta) ",
  mi: "Maori (New Zealand) ",
  mr: "Marathi (India) ",
  mn: "Mongolian (Mongolia) ",
  ns: "Northern Sotho (South Africa) ",
  nb: "Norwegian (Bokm?l) (Norway) ",
  nn: "Norwegian (Nynorsk) (Norway) ",
  ps: "Pashto (Afghanistan) ",
  pl: "Polish (Poland) ",
  pt: "Portuguese (Portugal) ",
  pa: "Punjabi (India) ",
  qu: "Quechua (Peru) ",
  ro: "Romanian (Romania) ",
  ru: "Russian (Russia) ",
  se: "Sami (Southern) (Sweden) ",
  sa: "Sanskrit (India) ",
  sr: "Serbian (Cyrillic) (Serbia and Montenegro) ",
  sl: "Slovenian (Slovenia) ",
  es: "Spanish (Spain) ",
  sw: "Swahili (Kenya) ",
  sv: "Swedish (Sweden) ",
  syr: "Syriac (Syria) ",
  tl: "Tagalog (Philippines) ",
  tt: "Tatar (Russia) ",
  ta: "Tamil (India) ",
  te: "Telugu (India) ",
  th: "Thai (Thailand) ",
  ts: "Tsonga ",
  tn: "Tswana (South Africa) ",
  tr: "Turkish (Turkey) ",
  uk: "Ukrainian (Ukraine) ",
  ur: "Urdu (Islamic Republic of Pakistan) ",
  uz: "Uzbek (Cyrillic) (Uzbekistan) ",
  vi: "Vietnamese (Viet Nam) ",
  cy: "Welsh (United Kingdom) ",
  xh: "Xhosa (South Africa) ",
  zu: "Zulu (South Africa) ",
};

export const languagesArray: { key: string; value: string }[] = Object.keys(
  languagesObj
).map((key) => ({
  key: key,
  value: languagesObj[key],
}));
